# Generated by Django 3.1.6 on 2021-02-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20210221_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todoCreator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
